language: node_js
node_js:
  - "0.10"
  - "6"
  - "8"
  - "10"
  - "11"
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - |
    if [[ "${TRAVIS_NODE_VERSION}" == "0.10" ]]; then
      npm run test-0.10
    else
      npm test
    fi
